#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/berry/sxhkdrc &

# Single Monitor
berryc save_monitor 0 0
berryc save_monitor 1 0
berryc save_monitor 2 0
berryc save_monitor 3 0
berryc save_monitor 4 0
berryc save_monitor 5 0
berryc save_monitor 6 0
berryc save_monitor 7 0
berryc save_monitor 8 0
berryc save_monitor 9 0

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 0
berryc title_height       35
# berryc top_gap            40
berryc edge_gap 20 60 20 20


# Set decoration colors
berryc focus_color         ffffff
berryc unfocus_color       ffffff
berryc inner_focus_color   ffffff
berryc inner_unfocus_color ffffff
berryc text_focus_color    050505
berryc text_unfocus_color  050505

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Cantarell-9"

$XDG_CONFIG_HOME/polybar/launch.sh
