#!/bin/sh

picom --config $XDG_CONFIG_HOME/picom/picom.conf --experimental-backends -b 
xrdb $XDG_CONFIG_HOME/Xresources &
xset r rate 450 50 &
xsetroot -cursor_name left_ptr &
unclutter &
clipmenud &
fehbg &
dual_monitor &
flameshot &
dunst &
mpd &
exec $WM
